lucide.createIcons();
const search=document.querySelector('.search input');
search.addEventListener('keydown',e=>{if(e.key==='Enter'&&search.value.trim())openAiExplainer(search.value.trim())});
const menuButton=document.querySelector('.menu'),todoPanel=document.querySelector('.todo-panel'),closeButton=document.querySelector('.todo-close'),todoForm=document.querySelector('.todo-form'),todoInput=document.querySelector('#new-todo'),todoList=document.querySelector('.todo-list'),todoCount=document.querySelector('.todo-count'),scrim=document.querySelector('.todo-scrim'),storageKey='momentum-todos';
let todos=[];try{todos=JSON.parse(localStorage.getItem(storageKey))||[]}catch{todos=[]}
const escapeHtml=text=>{const el=document.createElement('div');el.textContent=text;return el.innerHTML};
function saveTodos(){localStorage.setItem(storageKey,JSON.stringify(todos))}
function renderTodos(){todoList.innerHTML=todos.map(todo=>`<li class="todo-item ${todo.done?'is-complete':''}" data-id="${todo.id}"><label><input type="checkbox" ${todo.done?'checked':''} aria-label="Mark ${escapeHtml(todo.text)} as complete"><span class="todo-check"><i data-lucide="check"></i></span></label><span class="todo-text">${escapeHtml(todo.text)}</span><button class="todo-delete" type="button" aria-label="Delete ${escapeHtml(todo.text)}"><i data-lucide="x"></i></button></li>`).join('');const remaining=todos.filter(todo=>!todo.done).length;todoCount.textContent=todos.length?`${remaining} ${remaining===1?'task':'tasks'} remaining`:'';lucide.createIcons()}
function setPanel(open){document.body.classList.toggle('todo-open',open);menuButton.setAttribute('aria-expanded',open);todoPanel.setAttribute('aria-hidden',!open);if(open)todoInput.focus()}
menuButton.addEventListener('click',()=>setPanel(true));closeButton.addEventListener('click',()=>setPanel(false));scrim.addEventListener('click',()=>setPanel(false));
todoForm.addEventListener('submit',event=>{event.preventDefault();const text=todoInput.value.trim();if(!text)return;todos.unshift({id:Date.now().toString(),text,done:false});todoInput.value='';saveTodos();renderTodos();todoInput.focus()});
todoList.addEventListener('change',event=>{if(event.target.type!=='checkbox')return;const todo=todos.find(item=>item.id===event.target.closest('.todo-item').dataset.id);if(todo){todo.done=event.target.checked;saveTodos();renderTodos()}});
todoList.addEventListener('click',event=>{const button=event.target.closest('.todo-delete');if(!button)return;todos=todos.filter(todo=>todo.id!==button.closest('.todo-item').dataset.id);saveTodos();renderTodos()});
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&document.body.classList.contains('todo-open'))setPanel(false)});renderTodos();
const appleButton=document.querySelector('.left-button'),forestPanel=document.querySelector('.forest-panel'),pomodoroButton=document.querySelector('.pomodoro-trigger'),pomodoroPanel=document.querySelector('.pomodoro-panel'),pomodoroTask=document.querySelector('.pomodoro-task'),durationInput=document.querySelector('#focus-duration'),timerDisplay=document.querySelector('.timer-display'),timerStart=document.querySelector('.timer-start'),timerReset=document.querySelector('.timer-reset'),flowerBed=document.querySelector('.flowers');
const gardenKey='momentum-hydrangeas';let flowerCount=Number(localStorage.getItem(gardenKey))||0,secondsLeft=25*60,timerId=null;
function setCenterPanel(name,open){document.body.classList.toggle(`${name}-open`,open);const button=name==='forest'?appleButton:pomodoroButton;const panel=name==='forest'?forestPanel:pomodoroPanel;button.setAttribute('aria-expanded',open);panel.setAttribute('aria-hidden',!open);if(open&&name==='pomodoro')pomodoroTask.focus()}
function renderGarden(){flowerBed.innerHTML=Array.from({length:flowerCount},()=>'<div class="hydrangea" aria-label="Double-petal hydrangea"><span></span></div>').join('')}
function updateTimer(){const mins=Math.floor(secondsLeft/60).toString().padStart(2,'0'),secs=(secondsLeft%60).toString().padStart(2,'0');timerDisplay.textContent=`${mins}:${secs}`}
function focusSeconds(){const minutes=Math.max(10,Math.min(180,Number(durationInput.value)||10));durationInput.value=minutes;return minutes*60}
function finishFocus(){clearInterval(timerId);timerId=null;durationInput.disabled=false;timerStart.innerHTML='<i data-lucide="play"></i><span>Start focus</span>';const text=pomodoroTask.value.trim()||'Pomodoro focus session';todos.unshift({id:Date.now().toString(),text,done:false});saveTodos();renderTodos();flowerCount++;localStorage.setItem(gardenKey,flowerCount);renderGarden();secondsLeft=focusSeconds();updateTimer();pomodoroTask.value='';setCenterPanel('pomodoro',false);setCenterPanel('forest',true)}
appleButton.addEventListener('click',()=>setCenterPanel('forest',true));pomodoroButton.addEventListener('click',()=>setCenterPanel('pomodoro',true));document.querySelectorAll('.panel-close').forEach(button=>button.addEventListener('click',()=>{setCenterPanel('forest',false);setCenterPanel('pomodoro',false)}));
durationInput.addEventListener('change',()=>{if(!timerId){secondsLeft=focusSeconds();updateTimer()}});timerStart.addEventListener('click',()=>{if(timerId){clearInterval(timerId);timerId=null;durationInput.disabled=false;timerStart.innerHTML='<i data-lucide="play"></i><span>Resume</span>';lucide.createIcons();return}if(secondsLeft===0)secondsLeft=focusSeconds();durationInput.disabled=true;timerId=setInterval(()=>{secondsLeft--;updateTimer();if(secondsLeft<=0)finishFocus()},1000);timerStart.innerHTML='<i data-lucide="pause"></i><span>Pause</span>';lucide.createIcons()});timerReset.addEventListener('click',()=>{clearInterval(timerId);timerId=null;durationInput.disabled=false;secondsLeft=focusSeconds();updateTimer();timerStart.innerHTML='<i data-lucide="play"></i><span>Start focus</span>';lucide.createIcons()});renderGarden();updateTimer();
const aiPanel=document.querySelector('.ai-panel'),sourcePanel=document.querySelector('.source-panel'),chatMessages=document.querySelector('.chat-messages'),chatForm=document.querySelector('.chat-form'),chatInput=document.querySelector('#chat-input'),sourceLinks=document.querySelector('.source-links'),sourceButton=document.querySelector('.ai-source-trigger'),aiVideosButton=document.querySelector('.ai-videos');let activeQuestion='';
function setAiPanel(name,open){document.body.classList.toggle(name,open);const panel=name==='ai-open'?aiPanel:sourcePanel;panel.setAttribute('aria-hidden',!open)}
function addBubble(role,text,allowMarkup=false){const bubble=document.createElement('div');bubble.className=`chat-bubble ${role}`;if(allowMarkup)bubble.innerHTML=text;else bubble.textContent=text;chatMessages.append(bubble);chatMessages.scrollTop=chatMessages.scrollHeight;return bubble}
function friendlyFallback(question){return `<strong>Absolutely — let’s make this feel less tangled. ✨</strong><br><br><strong>The big idea:</strong> ${escapeHtml(question)} can be easier when we turn it into a few small questions instead of one huge one.<br><br><strong>Try this next:</strong><br>1. What is the main idea?<br>2. What causes it or makes it work?<br>3. What is one real-world example?<br><br>🧠 You do not need to understand every detail at once. Pick one step, pause, then come back for the next.`}
async function replyToQuestion(question){addBubble('user',question);const thinking=addBubble('assistant','Thinking it through… ✨');try{const response=await fetch('/api/explain',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question,style:'Reply like a kind, detailed ChatGPT tutor for neurodivergent learners. Use short sections, direct language, examples, and a few emojis. Do not make medical claims.'})});if(!response.ok)throw new Error('No AI endpoint');const data=await response.json();if(!data.answer)throw new Error('Empty AI response');thinking.textContent=data.answer}catch{thinking.innerHTML=friendlyFallback(question)}}
function openAiExplainer(question){activeQuestion=question;chatMessages.innerHTML='';setAiPanel('ai-open',true);replyToQuestion(question)}
function showSources(){if(!activeQuestion){search.focus();return}const q=encodeURIComponent(activeQuestion);const resources=[['Khan Academy on YouTube','Classroom-style explanations',`https://www.youtube.com/results?search_query=Khan+Academy+${q}`],['Crash Course on YouTube','Visual topic overviews',`https://www.youtube.com/results?search_query=Crash+Course+${q}`],['TED-Ed on YouTube','Animated lessons',`https://www.youtube.com/results?search_query=TED-Ed+${q}`],['YouTube results','Videos for your exact question',`https://www.youtube.com/results?search_query=${q}+explained`]];sourceLinks.innerHTML=resources.map(([name,description,url])=>`<a class="source-link" href="${url}" target="_blank" rel="noopener noreferrer"><i data-lucide="youtube"></i><div><b>${name}</b><span>${description}</span></div></a>`).join('');setAiPanel('sources-open',true);lucide.createIcons()}
sourceButton.addEventListener('click',showSources);aiVideosButton.addEventListener('click',showSources);chatForm.addEventListener('submit',event=>{event.preventDefault();const question=chatInput.value.trim();if(!question)return;activeQuestion=question;chatInput.value='';replyToQuestion(question)});document.querySelector('.ai-panel .panel-close').addEventListener('click',()=>setAiPanel('ai-open',false));document.querySelector('.source-panel .panel-close').addEventListener('click',()=>setAiPanel('sources-open',false));document.addEventListener('keydown',event=>{if(event.key==='Escape'){setAiPanel('ai-open',false);setAiPanel('sources-open',false)}});
